#!/bin/sh
copy() {
        scp -r * kipr@192.168.125.1:~/Documents/KISS/$1
}
shell() {
        ssh kipr@192.168.125.1
}
crosscomp() {
        sudo aarch64-linux-gnu-g++ -std=c++17 -g \
        -I"include/*" -I \
        "/usr/local/include/include" \
        -Wall "src/*.cpp" -L"/usr/local/lib" \
        -lkipr -lm -o "bin/botball_user_program" \
        -lz -lpthread
}
comp() {
        sudo g++ -std=c++17 -g \
        -I"include/*" -I \
        "/usr/local/include/include" \
        -Wall "src/*.cpp" -L"/usr/local/lib" \
        -lkipr -lm -o "bin/botball_user_program" \
        -lz -lpthread
}
